### ISSUE TITLE
LDAP login not working if local user with same name exists

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#117]
Proposal: 
- If LDAP is enabled, only LDAP logins shoud be used.
- Only Admin will remain local user

Maybe remove the possibility to switch (local login, ldap login)?

**Comment by oneiros** [comment]
> LDAP login not working if local user with same name exists

What exactly does "not working" mean?

LDAP is only used for authentication. If the LDAP server says a user is authentic, the database is searched for an existing user with the same email address. If such a user exists, this user is signed in. If no such user exists, a new (regular) user is created in the database.

**Comment by tuxmea** [comment]
According to customer the login does not work once you add a local user and later on switch to ldap.
LDAP is working again, once the local user has been removed.
