### ISSUE TITLE
Foreman HDM integration

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#132]
Check possibilities for a HDM-Foreman integration.
Design pattern insist that Foreman is talking to a Smart-Proxy only.

We might need:
- HDM API
- HDM Smart-Proxy
- HDM Foreman Web UI

Foreman HDM WebUI queries information from HDM Smart-Proxy.
HDM Smart-Proxy queries information from HDM API.

Foreman HDM Web UI should display in the same way as we do it in HDM.
User authentication is done by Foreman.

**Comment by tuxmea** [comment]
Links from Ewoud to Foreman Information:
- https://github.com/theforeman/smart-proxy/blob/2d9cdce590a2c3a3a9c5f0fd8e881082e85e9650/modules/dns/dns_api.rb#L4
- https://github.com/theforeman/smart_proxy_plugin_template
- https://theforeman.org/2019/04/smart-proxy-capabilities-explained.html
- https://github.com/theforeman/foreman_puppet
- https://github.com/theforeman/smart-proxy/tree/develop/modules
- https://github.com/theforeman/smart-proxy/tree/develop/modules
- https://github.com/theforeman/foreman_puppet/blob/master/webpack/src/Extends/Host/PuppetTab/index.js
- https://github.com/theforeman/smart-proxy/blob/develop/modules/templates/templates_unattended_api.rb
- https://github.com/theforeman/smart-proxy/blob/develop/modules/httpboot/http_config.ru

**Comment by tuxmea** [comment]
Vagrant instance: https://github.com/betadots/foreman-training

**Comment by oneiros** [comment]
Short update: I successfully created a (small, incomplete) smart proxy plugin. This was relatively easy. I am now struggling with creating a foreman plugin which, sadly,  is considerably more complex.

Among other things I started looking into how to integrate into the UI. I remember we talked about adding an "HDM"-Tab to the host's view. But I am not 100% sure where we said that tab should be placed. I think we talked about having it as a Sub-Tab on the "Puppet"-Tab (circled in red below). Is that correct? Or would it be OK to have it as a separate Tab next to "Puppet" (green arrow)?

![Screenshot 2023-05-17 at 14-39-30 lucy-sharbono foreman localhost](https://github.com/betadots/hdm/assets/68106/a9f612a2-d5f0-48cf-bd27-01bc5214e66c)

(As you can see, I managed to add a sub-tab on the puppet view. However, for top-level tabs foreman has a defined API to integrate plugins. The `foreman_puppet` plugin has no such thing and my approach here might be a bit brittle.)

**Comment by tuxmea** [comment]
@ekohl can you provide a good starting point for implementing HDM in Foreman?

**Comment by oneiros** [comment]
> @ekohl can you provide a good starting point for implementing HDM in Foreman?

No need. I am quite far along already. I think I (finally) got the basics. I can already query HDM from foreman via the smart proxy. I now need to figure out controller permissions and then build out a couple of react components to display the data.

**Comment by oneiros** [comment]
I just pushed an early prototype to the repo at https://github.com/betadots/foreman_hdm

Here is a screenshot:

![image](https://github.com/betadots/hdm/assets/68106/54c89f24-0999-4bd6-b64b-87039d3e86e3)

There is still a lot of rough edges and I still do not know how to install this plugin into a running foreman production installation, but maybe someone would like to take this for a test drive.

I took a lot of inspiration from the forman_salt plugin, that solves similar problems. One of these is how to determine the correct smart proxy for a given host. I solved this similarly to foreman_salt and add a new attribute `hdm_proxy` to each host. So you need to configure your smart proxy once and then set it on each host that should use it. The `HDM` tab on the host detail page is only shown if an `hdm_proxy` has been configured for that host.

**Comment by ekohl** [comment]
@oneiros looks very nice! I'm about go on vacation so won't have time to review it soon, so just know I'm not intentionally ignoring you.

Just looking at the screenshot I would consider using a monospace font for the eyaml hierachy.

Considering the top level tab vs HDM: I think that's a good starting point. We can look expanding foreman_puppet later but making it a standalone plugin for now is a good start.

**Comment by tuxmea** [comment]
Already implemented and working. Closing.
