### ISSUE TITLE
show unused environments

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#140]
get all environments from puppetdb even if no node is running against it

**Comment by tuxmea** [comment]
# Show unused envs

The actual state of HDM works as follows:
HDM reads from PuppetDB which environments are in use (by at least one node which did a complete puppet agent run).
Only after a complete Puppet agent run, the PuppetDB has all data for that node (environment, facts, reports).
Once we select an environment, we read the nodes facts which use the selected environment.

Now we want to also show unused Puppet environments.
Unused environments are located on the filesystem, but don't show up in PuppetDB.
Within HDM we should mark the unused environment (e.g. by prefixing the string 'unused')
When selecting an unused environment, we want the user to select ANY node from the node list.
On unused environments no data changes should be possible (read-only mode).

# 2nd use case:
Which hiera data does the node retrieve if the node switches its environment?

# Solution:

As we want to achieve different results for different use cases we came up with the following proposal:

1. Environments:
- read all environments from file system
- read environments from PuppetDB
- mark unused environments

1. Nodes
- we need a toogle switch which defaults to "show nodes from env only" and which can be set to "all nodes"
- Node list then shows nodes depending on toggle.

API endpoints to use:  https://www.puppet.com/docs/puppetdb/7/api/query/v4/nodes.html#pdbqueryv4nodesnodefacts

**Comment by oneiros** [comment]
I am currently struggling with our test data here as we reuse node names between environment. So just to confirm: In an actual production environment a node can only belong to one environment, correct?

**Comment by oneiros** [comment]
I _believe_ my assumption above is OK, so I went ahead and moved test data around a lot, but with a different approach as outlined above: I put all existing nodes in the `development` environment, created 25 new nodes in all other environments that had the full set formerly and 5 nodes in the one case where it only had a handfull before.

Tests work fine so far, so I created #146.
