### ISSUE TITLE
Edge case: PuppetDB still has an information regarding an environment, but the environment does no longer exist on file system

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#147]
Usually we have short living feature branch based environments.

Consider that someone creates the feature branch, runs a single node against the feature branch, and merges his change.
In this case the code deployment will remove the feature branch environment from file system, PuppetDB will get updated, when Puppet agent is running the next time.

Within HDM:

1. we get a list of environments from PuppetDB
2. we select an environment and query PuppetDB for nodes

Desired solution:

1. HDM queries PuppetDB for environments
2. prior showing the list HDM checks if any of the returned environments is no longer available on file system and marks the unavailable environments as non-selectable in the drop-down menu

**Comment by ghoneycutt** [comment]
A better source of truth for environments would be to ask the servers hosting code instead of PuppetDB. https://www.puppet.com/docs/puppet/7/http_api/http_environments.html
