### ISSUE TITLE
Show current used values when selecting nodes from different environment

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#151]
When selecting a hiera key from an environment which is not used by the selected node (node shows its current environment) I want to be able to see the current value (which is the value from the nodes last used environment) next to the value which would be used in the selected environment. This can be side-by-side or only unified diff.

example with an unused environment.

env: `feature_33b4 (unused)`
node: `puppet.domain.tld (production)`

select hiera key:  `classes_hash`
open `common.yaml`

we see a table. left column shows values from `feature_33b4` environment, right column shows values from `production` environment
or
we show a unified diff.

Optional:
add a switch which activates the default values column.

Solution should also work on a used env but the nodes uses another one.

Read-Write mode:

When HDM is configued in read-write mode, we also should have a switch which changes from the value to a diff. When showing a diff, the edit function should be disabled. When switching back to value view, the edit should be possible again.
If someone wants to switch from edit to diff, we should show a warning that changes will be lost.

**Comment by oneiros** [comment]
Thinking about this some more, I wonder how and if this is even possible.

We currently only display values per file:
A user selects an environment, a node and a key and then we display a list of hierarchies and files within that hierarchy. The user then selects one of those files belonging to a hierarchy and can then (and only then) see the applicable value.

If I choose a different environment from the node's current environment, I am free to explore what would happen, if the node were placed in that environment. But there is no guarantee that this environment has the same hierarchies and files. One environment might have a `common.yaml` as the base of the hierarchy, while another might have no such file. Yet another environment might have a `common.yaml`, but at a completely different level of hierarchies. What is the "current" or "default" value in these scenarios?

I am not sure there is a solution to this that works in all cases, is reasonably easy to implement and not confusing to the user.

**Comment by tuxmea** [comment]
Let's keep this simple: if there is not the same file on the branch which we want to compare: just show that there is no file and dont show a diff.
