### ISSUE TITLE
HDM does not recognize the facts. syntax in hiera.yaml file

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#17]
In hiera.yaml file one can specify a fact in multiple ways.

1. Top Scope Variable (Using :: syntax like %{::customer})
2. Facts Hash (Using facts. syntax like %{facts.customer})

At the moment HDM only recognizes option 1.
HDM should be able to also understand and parse the option 2.

Some people might use %{::environment} in Hiera.yaml.
This is not a fact but should have the content from the selected environment.

**Comment by rwaffen** [comment]
names to get facts from in hiera.yaml:
- facts (facts.customer)
- server_facts (server_facts.)
- trusted (trusted.certname)
- `::` (top scope)

hierachies can be mixed:

`customer/%{facts.customer}/%{trusted.certname}.yaml`

**Comment by rwaffen** [comment]
# Gültige formulierungen

```
::facts.customer
facts.customer
::trusted.irgendetwas
trusted.irgendetwas
```

`::customer`
- kann man nicht feststellen was es wirklich ist, ob nun fact oder wirklich eine top scope variable
- erstmal ausklammern, da kompliziert zu filtern
- für jedes environment alle facts für all hosts holen und alles was dort nicht genannt wird ist eine top scope variable
