### ISSUE TITLE
Initial start up page

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#234]
To make it easier for users understanding the initial setup and config possibilities, we want to offer an initial start up page.

Content A (authentication disabled):
```
Welcome to HDM

You have configured HDM without authentication.

Continue [here] <- link to select environment
For local authentication or LDAP/AD you must configure HDM config file.
See https://github.com/betadots/hdm/blob/92219b98f48e29d9c2c9b64d8b8f0996e58d88c5/config/hdm.yml.template#L55
```

Content B (local auth - how does LDAP work?):
```
Welcome to HDM

You can configure access locally or via LDAP/AD.

For local user management click (here).

For LDAP/AD you must configure HDM config file.
See https://github.com/betadots/hdm/blob/92219b98f48e29d9c2c9b64d8b8f0996e58d88c5/config/hdm.yml.template#L55
```

**Comment by oneiros** [comment]
I was not 100% certain how to go about this. First of all there are a couple of cases we need to keep distinct:

1. No user (neither admin nor regular) exists.
2. The initial admin user exists, but no regular user.
3. Both admin and regular users exist.

In case 1 the user was redirected to the form to create a new user with a very short message to create an admin user.

I think this is the case where a page like mentioned above makes most sense.

But I think the wording above is misleading, becaue even when using LDAP/AD, you still should create an admin user. Also, we have SAML as an additional option not mentioned above.

So this is what I came up with:

![Screenshot 2024-01-18 at 10-46-40 HDM](https://github.com/betadots/hdm/assets/68106/aa40025f-9cb1-4aa6-b459-06527e15dc6c)

In case two, we already have a message to inform the user of the necessary next step:

![Screenshot 2024-01-18 at 10-47-39 HDM](https://github.com/betadots/hdm/assets/68106/8f5038cb-08ba-49c4-a8ee-c77dc4cb026c)

I think it might make sense to repeat the same information about alternative authentication for regular users here. wdyt?

In case 3 we go straight to the login form. I took the liberty to amend the layout of this to match the one above. This reduces the space the logo takes up significantly and thus makes better use of screen real estate imo.

![Screenshot 2024-01-18 at 10-48-39 HDM](https://github.com/betadots/hdm/assets/68106/35a356a7-15e3-4658-9414-5a076a796424)

Thinking some more about this, I think we need to skip at least some of case 1 and all of case 2 when either LDAP or SAML is already configured.

Also, we need to consider that no authentication is required, as you point out in the edited description.
