### ISSUE TITLE
New feature: Show data result

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#264]
### Discussed in https://github.com/betadots/hdm/discussions/241

<div type='discussions-op-text'>

<sup>Originally posted by **tuxmea** December 22, 2023</sup>
## Request

```text
As a Puppet admin I want to be able to see the result of the lookup.
```

## Solution

After selecting a key a new button shows up (or gets enabled) with title "result".
Upon clicking an overlay windows presents the complete result, based on lookup_options.
</div>

**Comment by bastelfreak** [comment]
As discussed in our meeting, here are some background infos:
* The puppet DSL lookup function: https://github.com/puppetlabs/puppet/blob/main/lib/puppet/functions/lookup.rb
* The internal implementation: https://github.com/puppetlabs/puppet/blob/main/lib/puppet/functions/lookup.rb
* The `puppet lookup CLI`:https://github.com/puppetlabs/puppet/blob/main/lib/puppet/application/lookup.rb

**Comment by oneiros** [comment]
Quick question: If I try to lookup a simple scalar value, e.g. an integer, but request a merge strategy of `unique` or `deep`, will this result in an error?

**Comment by bastelfreak** [comment]
@oneiros no, that's allowed for unique: https://www.puppet.com/docs/puppet/8/hiera_merging#merge_behaviors

> A unique merge (also called an array merge) combines any number of array and scalar (string, number, boolean) values to return a merged, flattened array with all matching values for a key. All duplicate values are removed. The lookup fails if any of the values are hashes. The result is ordered from highest priority to lowest.

For `deep` I'm not sure in the moment and need to test it.

**Comment by tuxmea** [comment]
AFAIK we can close this issue as this is implemented.

**Comment by tuxmea** [comment]
Implemented. Closing
