### ISSUE TITLE
Cleanup existing rubocop violations

### ISSUE THREAD

**Issue by bastelfreak** [betadots/hdm#29]
We currently have a bunch of rubocop violations listed in https://github.com/betadots/hdm/blob/main/.rubocop_todo.yml. This needs to be fixed or we need to disable cops we do not like.

**Comment by rwaffen** [comment]
see: https://github.com/betadots/hdm/pull/33/files

**Comment by tuxmea** [comment]
We are going to work on the single todos on a cop by cop or file by file basis.

**Comment by tuxmea** [comment]
This is permanent WIP. Closing this issue
