### ISSUE TITLE
Define a CI/CD strategy

### ISSUE THREAD

**Issue by bastelfreak** [betadots/hdm#3]
Some thoughts about a CI/CD strategy that could be implemented. This is based on my experience with vox-pupuli-tasks (also a Rails application) and the different gems Vox Pupuli hosts:

## Enable dependabot alerts

  *  GitHub will scan the Gemfile.lock for potential updates and CVEs in dependencies daily

## Define a GitHub action that runs on pull requests:

* Define the lowest Rubyversion we support
* Run rubocop with that Rubyversion as target
* Define a list of Ruby versions we want to support + latest ruby
* Use that as a matrix where we run the following for each ruby version
* Run the existing rspec tests in a matrix on each Ruby version
  * On one Ruby version, run codecov for coverage reporting
  * Run brakeman for Rails specific reporting
* build the application (generating assets...)
* Start the application and validate some http endpoints

## Define a GitHub action that runs on merges

* Apply the action from above
* Build a docker image
  * publish it at least to github container registry
  * Tag the image with the commit sha
  * Tag it also with latest or testing
  * Start the application via docker-compose with the new Image+dependencies
* build at least rpms+debs and upload them

## Define a GitHub action that runs on tags

* same as above, but tag packages/images with the name of the pushed tag, not a commit sha

## Additional Resources

* https://github.com/voxpupuli/vox-pupuli-tasks/blob/master/.github/workflows/test-build.yml
* https://github.com/voxpupuli/vox-pupuli-tasks/blob/master/.github/workflows/test-build-release.yml
* https://github.com/voxpupuli/beaker/blob/master/.github/workflows/test.yml
* https://github.com/voxpupuli/vox-pupuli-tasks/commit/32e8c7d9f28e2b3ee4f418d7d655fdcb1f864e8a

**Comment by tuxmea** [comment]
Additional: Test with different Puppet versions and the according ruby versions.
https://puppet.com/docs/puppet/6/platform_lifecycle.html#puppet-agent-components
https://puppet.com/docs/puppet/7/platform_lifecycle.html#component-version-numbers

## Puppet 6:
- 6.1.x - 6.10.0 - Ruby 2.5.3
- 6.10.1 - 6.21.1 - Ruby 2.5.7
- 6.22.1 - 6.x - Ruby 2.5.9

## Puppet 7
7.0.0 - 7.7.0 - Ruby 2.7.0
7.9.0 - 7.13.1 - Ruby 2.7.3
7.14.0 - 7.x - Ruby 2.7.5

## Puppet 8
- Ruby 3?

**Comment by tuxmea** [comment]
Test will be run on Ruby Major-Minor Version. No tests and builds for patchlevel versions.
- Ruby 2.5 - Puppet 6
- Ruby 2.7 - Puppet 7

We try to NOT build OS specific Packages.

**Comment by bastelfreak** [comment]
I think this is now properly implemented.
