### ISSUE TITLE
New feature: comparing data for a node between environments

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#301]
### Discussed in https://github.com/betadots/hdm/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **tuxmea** December 22, 2023</sup>
## Request

As a Puppet admin I want to compare data between two environments in case that a node receives different settings from environment A compared to environment B

## Solution 1

Select environment -> node -> Key

A new pull down menu shows up (or gets enabled) with the title "compare".
Content are the available environments.
After selecting the second environment, a new pane opens with the hierarchies and the data per hierachy for the selected key.

## Solution 2

Based on #241 
When showing the result set, we also add a "compare" pull down menu.
Data are shown left (actual environment) and right (selected comparing environment).

Optional with the possibility to synchronize scrolling.
</div>

As files and keys might have moved from env A to env B, we only want to compare the result as mentioned in Solution2.

**Comment by oneiros** [comment]
Solved with #320
