### ISSUE TITLE
Update to Ruby 3.3.0?

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#305]
can, shall we update to ruby 3.3.0?

**Comment by bastelfreak** [comment]
Latest is greatest! IMO we should update as soon as Rails supports it.

**Comment by oneiros** [comment]
Rails support should not be an issue. Last time we discussed this, I was a bit hesitant, bevause the `.0` versions sometimes had issues in the past.

But it has been two months, I know of huge companies running 3.3 in production, and nothing has come up thus far that I am aware of. So let us do it.

**Comment by rwaffen** [comment]
okay, will prepare a PR for this.
