### ISSUE TITLE
CI Bug with google-protobuf-3.25.2-x86_64-linux 

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#313]
`google-protobuf-3.25.2-x86_64-linux` is incopatible with ruby 3.3.0. Somehow this got throught without us noticing while doing the update of ruby ¯\_(ツ)_/¯ 

this has the effect that our ci steps are failing which use the Gemfile and try to install the protobuf gem

**Comment by rwaffen** [comment]
see: https://github.com/betadots/hdm/actions/runs/8081337150/job/22079660537?pr=312
https://github.com/betadots/hdm/pull/312#event-11951906543

**Comment by oneiros** [comment]
I had to fix this in the branch `issue-264` while rebasing against `main`. So this should go away when #283 is merged.

**Comment by rwaffen** [comment]
we also fixed it in #315 🤦 😄

**Comment by rwaffen** [comment]
Fixed by #283
