### ISSUE TITLE
Add version to footer

### ISSUE THREAD

**Issue by tuxmea** [betadots/hdm#340]
When opening the HDM webpage I would like to see which version is used.
Version should be based on the GIT Tag or read from a file.

**Comment by oneiros** [comment]
I remember we discussed setting a `VERSION` constant inside of a rails inititalizer (something like `config/inititalizers/version.rb`). This is evaluated once on startup. At this point we could simply shell out to `git` to try to get a version number.

But I wonder, do we always have a `git` command *and* a git repo? Even in docker?

**Comment by rwaffen** [comment]
we added git some time ago when we had this idea with the seperated git repository to write back data and not change it in the local data dir.

**Comment by rwaffen** [comment]
@tuxmea its nice to have, so that you know exactly what is installed/used
