### ISSUE TITLE
Use YJIT in our Container

### ISSUE THREAD

**Issue by bastelfreak** [betadots/hdm#362]
Shopify worked on compiler improvements for Ruby: https://github.com/Shopify/yjit
This was merged upstream in Ruby 3.1 and got a lot of improvements in Ruby 3.3. We now use 3.3 in our container images so we should check if our application is compatible with the new compiler and use it. Some background information: https://dev.to/colinsoleim/supercharging-rails-enabling-rubys-yjit-compiler-in-production-56o0. The Ruby container we use already has it enabled: https://github.com/docker-library/ruby/blob/77efb18a0fb15955a4f77c9fa1d3968875915b78/3.3/bookworm/Dockerfile#L37-L57

**Comment by tuxmea** [comment]
Please check how much extra RAM is needed

**Comment by rwaffen** [comment]
will implement this in the dockerfile
