### ISSUE TITLE
Setup integration environment for testing/developing

### ISSUE THREAD

**Issue by rwaffen** [betadots/hdm#47]
- setup pe main server
- setup pe puppetdb
- add sample data/control_repo
- use vagrant (?)
- use docker(?)

**Comment by SimonHoenscheid** [comment]
terraform based for Hcloud?

**Comment by tuxmea** [comment]
Should be done using vagrant and the workshop control-repo.
Our Puppet Primary already has DockerD running (Puppetboard). We can use this DockerD also for HDM
